### ISSUE TITLE
Model weights?

### ISSUE THREAD

**Issue by tripathiarpan20** [ilaria-manco/muscall#1]
Hi!
Really amazing work! I believe it has the potential for providing CLIP guidance to an Audio Diffusion model for getting text-to-music models. The Diffusion model would have to be Latent Diffusion model though for generating songs of appreciable length (maybe borrowing some ideas from Jukebox will do).

For making the above work possible, would the model weights be publicly available?
Thanks

**Comment by zihaohe123** [comment]
+1

**Comment by ilaria-manco** [comment]
Hi @tripathiarpan20, thank you very much for your interest in our work.

Unfortunately I won't be able to share the weights as the model was trained on a private dataset.
