### ISSUE TITLE
Please share preprocessing steps of audio wav/mp3

### ISSUE THREAD

**Issue by aryancodify** [ilaria-manco/muscall#3]
Hi @ilaria-manco 

It would be great if you can share the audio file pre-processing steps before saving them into the .npy format for training.

Thanks
Aryan

**Comment by ilaria-manco** [comment]
Hi @aryancodify, thank you for opening this issue.

The preprocessing is similar to the steps outlined in this [README](https://github.com/ilaria-manco/muscaps/blob/main/data/README.md):

```python
import os
import librosa
import numpy as np

audio_dir = "data/datasets/audiocaption/audio"
for audio_file in os.listdir(audio_dir):
    audio_path = os.path.join(audio_dir, audio_file)
    audio, sr = librosa.load(audio_path, 16000)
    array_path = audio_path.replace("wav", "npy")
    np.save(open(array_path, 'wb'), audio)
```

I hope this helps!
